#framework:
#    default_locale: 'en'
#   translator:
#        fallbacks: ['en']
#        #paths:
#        #     - '%kernel.project_dir%/translations'
#

framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
