index:
    path: /
    controller: App\Controller\TechNews\IndexController::index

#route redirection
accueil:
    path: /home
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
      route: index
      permanent: true

#static redirection
mentions_legales:
    path:         /privacy
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/privacy.html.twig