index:
    path: /
    controller: App\Controller\TechNews\IndexController::index

test:
    path: /test.html
    controller: App\Controller\TechNews\IndexController::test

#route redirection
home:
    path: /home
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
      route: index
      permanent: true

#static redirection
privacy:
    path:         /privacy
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/privacy.html.twig